import type { Metadata } from 'next'
import './globals.scss'
import { Source_Sans_3, Source_Serif_4 } from 'next/font/google'
import localFont from 'next/font/local'

const source_serif_4 = Source_Serif_4({
	display: 'swap',
	subsets: ['latin'],
	variable: '--font-source-serif-4',
})

const source_sans_3 = Source_Sans_3({
	display: 'swap',
	subsets: ['latin'],
	variable: '--font-source-sans-3',
})

// Source Serif 4 not fitting the desired effect, especially for titles, so loading previous Source Serif Pro locally instead
// const source_serif_pro = localFont({
// 	src: [
// 		{
// 			path: './assets/fonts/SourceSerifPro/SourceSerifPro-Black.ttf',
// 			weight: '900',
// 			style: 'normal',
// 		},
// 		{
// 			path: './assets/fonts/SourceSerifPro/SourceSerifPro-Regular.ttf',
// 			weight: '400',
// 			style: 'normal',
// 		},
// 	],
// 	variable: '--font-source-serif-pro',
// })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='fr'>
			<body className={`${source_serif_4.variable} ${source_sans_3.variable} font-serif`}>{children}</body>
		</html>
	)
}
